name: Parallelization with Win,Ubuntu,maCOS
'on':
  workflow_dispatch: 
#   pull_request:
#     branches:
#       - master
#     schedule:
#       - cron: '* 5 * * *'
jobs:
  Google-Test:
    strategy:
      matrix:
       version: [16]
       os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i cypress@10.9.0 && npm install 
      - run: npx cypress run --browser=electron --parallel --group=Linux/Electron --record --key= ${{ secrets.RECORD_KEY }} || node cucumber-html-report.js  
      - run: npx cypress run --browser=chrome --parallel --group=Windows/Chrome-69 --record --key= ${{ secrets.RECORD_KEY }} || node cucumber-html-report.js
      - run: npx cypress run --browser=chrome --parallel --group=Mac/Chrome-70 --record --key= ${{ secrets.RECORD_KEY }} || node cucumber-html-report.js
        env:          
           CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
