
name: run-cypress-parallelization_with_chrome
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
#   push:
#     branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      job: [0, 1, 2]
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:10.9.0
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm i cypress@10.9.0 && npm install && ${{ secrets.RUN_COMMAND }}
      - run: npx cypress run --browser=chrome configFile=qa --record --parallel --key=${{ secrets.RECOVERY_KEY }
